const translations = {
    en: {
        title: "About Samarkand - Silk Road's Jewel",
        header_title: "Samarkand",
        nav_history: "History",
        nav_landmarks: "Landmarks",
        nav_museums: "Museums",
        nav_gallery: "Gallery",
        hero_title: "Discover Samarkand",
        hero_text: "Journey to the heart of the Silk Road, where history and culture intertwine in timeless splendor.",
        hero_cta: "Explore Now",

        history_title: "History of Samarkand",
        history_8bc_title: "8th Century BC",
        history_8bc_text: "Founded as Marakanda, Samarkand becomes the capital of Sogdiana, as noted in the Zoroastrian 'Avesta.'",
        history_sasanian_title: "3rd–7th Century",
        history_sasanian_text: "During the Sasanian era, Samarkand remained a key cultural and trading hub of Central Asia.",
        history_329bc_title: "329 BC",
        history_329bc_text: "Alexander the Great conquers Samarkand, highlighting its strategic value along the Great Silk Road.",
        history_samanid_title: "9th–10th Century",
        history_samanid_text: "Under the Samanid Empire, Samarkand flourishes as a center of science, medicine, and literature in the Islamic Golden Age.",
        history_14c_title: "14th Century",
        history_14c_text: "Amir Timur makes Samarkand the capital of his empire, ushering in a golden age of culture and architecture.",
        history_1868_title: "1868",
        history_1868_text: "Russian forces conquer Samarkand, integrating it into the Russian Empire.",
        history_1925_title: "1925–1939",
        history_1925_text: "Samarkand serves as Uzbekistan’s capital, later becoming a UNESCO World Heritage Site.",

        landmarks_title: "Landmarks & Wonders",
        landmarks_text: "Discover Samarkand’s architectural masterpieces, adorned with intricate tilework and majestic domes.",
        landmark_registan_title: "Registan Square",
        landmark_registan_text: "A UNESCO World Heritage Site, featuring the Ulugbek (1420), Sherdor (1636), and Tillya-Kari (1660) madrassahs.",
        landmark_guremir_title: "Gur-Emir Mausoleum",
        landmark_guremir_text: "Built in 1404, this mausoleum houses Amir Timur’s tomb, famed for its turquoise dome.",
        landmark_bibikhanum_title: "Bibi-Khanum Mosque",
        landmark_bibikhanum_text: "Constructed in 1404 for Amir Timur’s wife, featuring a grand stone Quran platform.",

        museums_title: "Museums of Samarkand",
        museums_text: "Explore Samarkand’s rich heritage through its museums, preserving ancient artifacts and stories.",
        museum_afrosiab_title: "Afrosiab Museum",
        museum_afrosiab_text: "Showcases 8th-century BC artifacts, including Samanid palace frescoes, near the ancient Afrosiab site.",
        museum_ulugbek_title: "Ulugbek Observatory Museum",
        museum_ulugbek_text: "Highlights Mirzo Ulugbek’s 15th-century astronomical achievements with a reconstructed observatory.",

        gallery_title: "Visual Splendor",
        gallery_text: "Immerse yourself in Samarkand’s vibrant beauty through these captivating images.",
        gallery_shahi_zinda: "Shahi Zinda",
        gallery_ulugbek: "Ulugbek Observatory",
        gallery_daniel: "Saint Daniel's Tomb",

        footer_text: "© 2025 About Samarkand. All rights reserved.",
        footer_contact: "Contact Us"
    },

    ru: {
        title: "О Самарканде — Жемчужина Шёлкового пути",
        header_title: "Самарканд",
        nav_history: "История",
        nav_landmarks: "Памятники",
        nav_museums: "Музеи",
        nav_gallery: "Галерея",
        hero_title: "Откройте Самарканд",
        hero_text: "Путешествие в сердце Шёлкового пути, где история и культура переплетаются в вечной красоте.",
        hero_cta: "Исследовать сейчас",

        history_title: "История Самарканда",
        history_8bc_title: "8 век до н.э.",
        history_8bc_text: "Основан как Мараканда, Самарканд становится столицей Согдианы, упомянут в зороастрийской 'Авесте'.",
        history_sasanian_title: "3–7 века",
        history_sasanian_text: "Во времена Сасанидов Самарканд оставался важным культурным и торговым центром Центральной Азии.",
        history_329bc_title: "329 год до н.э.",
        history_329bc_text: "Александр Македонский завоёвывает Самарканд, подчёркивая его стратегическое значение на Шёлковом пути.",
        history_samanid_title: "9–10 века",
        history_samanid_text: "При Саманидах Самарканд расцветает как центр науки, медицины и литературы в эпоху исламского Золотого века.",
        history_14c_title: "14 век",
        history_14c_text: "Амир Тимур делает Самарканд столицей своей империи, начав Золотой век культуры и архитектуры.",
        history_1868_title: "1868 год",
        history_1868_text: "Русские войска завоёвывают Самарканд, включая его в состав Российской Империи.",
        history_1925_title: "1925–1939",
        history_1925_text: "Самарканд был столицей Узбекистана, позже стал объектом Всемирного наследия ЮНЕСКО.",

        landmarks_title: "Памятники и чудеса",
        landmarks_text: "Откройте для себя архитектурные шедевры Самарканда, украшенные узорной плиткой и величественными куполами.",
        landmark_registan_title: "Площадь Регистан",
        landmark_registan_text: "Объект Всемирного наследия ЮНЕСКО с медресе Улугбека (1420), Шердор (1636) и Тилля-Кари (1660).",
        landmark_guremir_title: "Мавзолей Гур-Эмир",
        landmark_guremir_text: "Построен в 1404 году, здесь покоится Амир Тимур. Знаменит своим бирюзовым куполом.",
        landmark_bibikhanum_title: "Мечеть Биби-Ханым",
        landmark_bibikhanum_text: "Построена в 1404 году для жены Амира Тимура, с платформой для огромного каменного Корана.",

        museums_title: "Музеи Самарканда",
        museums_text: "Познакомьтесь с богатым наследием Самарканда через музеи, хранящие древние артефакты и истории.",
        museum_afrosiab_title: "Музей Афросиаб",
        museum_afrosiab_text: "Представляет артефакты 8 века до н.э., включая фрески дворца Саманидов у древнего поселения Афросиаб.",
        museum_ulugbek_title: "Музей Обсерватории Улугбека",
        museum_ulugbek_text: "Подчеркивает достижения Муртаза Улугбека в астрономии XV века с реконструированной обсерваторией.",

        gallery_title: "Визуальное великолепие",
        gallery_text: "Окунитесь в яркую красоту Самарканда с помощью этих захватывающих изображений.",
        gallery_shahi_zinda: "Шахи-Зинда",
        gallery_ulugbek: "Обсерватория Улугбека",
        gallery_daniel: "Гробница Святого Даниила",

        footer_text: "© 2025 О Самарканде. Все права защищены.",
        footer_contact: "Связаться с нами"
    },

    uz: {
        title: "Samarqand haqida — Ipak yo‘lining durdonasi",
        header_title: "Samarqand",
        nav_history: "Tarix",
        nav_landmarks: "Diqqatga sazovor joylar",
        nav_museums: "Muzeylar",
        nav_gallery: "Gallereya",
        hero_title: "Samarqandni kashf eting",
        hero_text: "Tarix va madaniyat uyg‘unlashgan Ipak yo‘li yuragiga sayohat qiling.",
        hero_cta: "Hozir o‘rganing",

        history_title: "Samarqand tarixi",
        history_8bc_title: "Miloddan avvalgi 8-asr",
        history_8bc_text: "Marokanda nomi bilan tashkil topgan, Zardushtiylarning 'Avesto'sida Sog‘diyona poytaxti sifatida tilga olingan.",
        history_sasanian_title: "3–7-asrlar",
        history_sasanian_text: "Sosoniylar davrida Samarqand Markaziy Osiyoning muhim madaniy va savdo markazi bo‘lib qolgan.",
        history_329bc_title: "Miloddan avvalgi 329-yil",
        history_329bc_text: "Iskandar Zulqarnayn Samarqandni zabt etadi va uning strategik ahamiyatini ko‘rsatadi.",
        history_samanid_title: "9–10-asrlar",
        history_samanid_text: "Somoniylar davrida Samarqand islom olamining ilm-fan, tibbiyot va adabiyot markaziga aylangan.",
        history_14c_title: "14-asr",
        history_14c_text: "Amir Temur Samarqandni o‘z imperiyasi poytaxti qilib, uni madaniyat va me’morchilik gullab-yashnagan shaharga aylantiradi.",
        history_1868_title: "1868-yil",
        history_1868_text: "Rossiya imperiyasi qo‘shinlari tomonidan egallangan va imperiya tarkibiga qo‘shilgan.",
        history_1925_title: "1925–1939-yillar",
        history_1925_text: "Samarqand O‘zbekiston poytaxti bo‘lib xizmat qiladi, keyinchalik YUNESKO merosi sifatida tan olinadi.",

        landmarks_title: "Diqqatga sazovor joylar",
        landmarks_text: "Nafis koshinlar va ulug‘vor gumbazlar bilan bezatilgan me’moriy mo‘jizalarni kashf eting.",
        landmark_registan_title: "Registon maydoni",
        landmark_registan_text: "YUNESKO merosi hisoblanadi; Ulug‘bek (1420), Sherdor (1636) va Tillakori (1660) madrasalari joylashgan.",
        landmark_guremir_title: "Go‘ri Amir maqbarasi",
        landmark_guremir_text: "1404-yilda qurilgan, Amir Temurning qabri shu yerda joylashgan. Uning moviy gumbazi mashhur.",
        landmark_bibikhanum_title: "Bibi-Xonim masjidi",
        landmark_bibikhanum_text: "1404-yilda Amir Temurning rafiqasi uchun qurilgan. Katta tosh Qur’on platformasiga ega.",

        museums_title: "Samarqand muzeylari",
        museums_text: "Qadimiy artefaktlar va tarixlarni saqlovchi muzeylar orqali Samarqand boy merosi bilan tanishing.",
        museum_afrosiab_title: "Afrosiyob muzeyi",
        museum_afrosiab_text: "Miloddan avvalgi 8-asr artefaktlarini, jumladan, Somoniylar saroyi devoriy rasmlarini namoyish etadi.",
        museum_ulugbek_title: "Ulug‘bek rasadxonasi muzeyi",
        museum_ulugbek_text: "Mirzo Ulug‘bekning XV asrdagi astronomik yutuqlari va rasadxona rekonstruksiyasi bilan tanishtiradi.",

        gallery_title: "Ko‘rgazmali go‘zallik",
        gallery_text: "Samarqandning betakror go‘zalligini ushbu fotosuratlar orqali his eting.",
        gallery_shahi_zinda: "Shohi Zinda",
        gallery_ulugbek: "Ulug‘bek rasadxonasi",
        gallery_daniel: "Doniyor payg‘ambarning qabri",

        footer_text: "© 2025 Samarqand haqida. Barcha huquqlar himoyalangan.",
        footer_contact: "Biz bilan bog‘laning"
    },

    tj: {
        title: "Дар бораи Самарқанд – Гавҳари Роҳи Абрешим",
        header_title: "Самарқанд",
        nav_history: "Таърих",
        nav_landmarks: "Ёдгориҳо",
        nav_museums: "Осорхонаҳо",
        nav_gallery: "Галерея",
        hero_title: "Самарқандро кашф намоед",
        hero_text: "Сафар ба қалби Роҳи Абрешим – ҷойе ки таърих ва фарҳанг дар шукӯҳи абадӣ якҷо мешаванд.",
        hero_cta: "Ҳозир омӯзед",

        history_title: "Таърихи Самарқанд",
        history_8bc_title: "Асри VIII пеш аз милод",
        history_8bc_text: "Самарқанд бо номи Мараканда таъсис ёфта, пойтахти Суғд гардид, чунон ки дар 'Авесто'-и зардуштиён зикр шудааст.",
        history_sasanian_title: "Асрҳои III–VII",
        history_sasanian_text: "Дар даврони Сосониён, Самарқанд маркази муҳими фарҳангӣ ва тиҷоратии Осиёи Марказӣ боқӣ монд.",
        history_329bc_title: "329 пеш аз милод",
        history_329bc_text: "Искандари Мақдунӣ Самарқандро фатҳ намуда, аҳамияти стратегӣ доштани онро дар Роҳи Абрешим таъкид кард.",
        history_samanid_title: "Асрҳои IX–X",
        history_samanid_text: "Дар замони Сомониён, Самарқанд маркази илм, тиб ва адабиёт дар Давраи Тиллоии Ислом гардид.",
        history_14c_title: "Асри XIV",
        history_14c_text: "Амир Темур Самарқандро пойтахти империяаш қарор дода, давраи нави тиллоии фарҳанг ва меъмориро оғоз кард.",
        history_1868_title: "Соли 1868",
        history_1868_text: "Қӯшунҳои рус Самарқандро забт карда, онро ба ҳайати Империяи Русия дохил намуданд.",
        history_1925_title: "Солҳои 1925–1939",
        history_1925_text: "Самарқанд муддате пойтахти Ҷумҳурии Ӯзбекистон буд ва баъдтар ба рӯйхати Мероси Ҷаҳонии ЮНЕСКО шомил гардид.",

        landmarks_title: "Ёдгориҳо ва муъҷизаҳо",
        landmarks_text: "Шоҳкориҳои меъмории Самарқандро кашф намоед – бо катифаи зебои кафел ва гумбазҳои бошукӯҳ.",
        landmark_registan_title: "Майдони Регистон",
        landmark_registan_text: "Мероси ҷаҳонии ЮНЕСКО, иборат аз мадрасаҳои Улуғбек (1420), Шердор (1636) ва Тиллокорӣ (1660).",
        landmark_guremir_title: "Мақбараи Гур-Амир",
        landmark_guremir_text: "Сохта дар соли 1404, оромгоҳи Амир Темур бо гумбази фирӯзафомаш машҳур аст.",
        landmark_bibikhanum_title: "Масҷиди Бибихонум",
        landmark_bibikhanum_text: "Соли 1404 барои ҳамсари Амир Темур бунёд ёфта, бо минбари бузурги сангини Қуръон шӯҳрат дорад.",

        museums_title: "Осорхонаҳои Самарқанд",
        museums_text: "Осорхонаҳои Самарқанд таърихи ғанӣ ва фарҳанги қадимро тавассути ашё ва ҳикояҳо ҳифз мекунанд.",
        museum_afrosiab_title: "Осорхонаи Афросиёб",
        museum_afrosiab_text: "Намоишгари ашёи асри VIII пеш аз милод, аз ҷумла наққошиҳои девории қасри Сомониён, воқеъ дар макони қадимаи Афросиёб.",
        museum_ulugbek_title: "Осорхонаи Расадхонаи Улуғбек",
        museum_ulugbek_text: "Комёбиҳои астрономии Мирзо Улуғбек дар асри XV бо расадхонаи дубора сохташуда ба тамошо гузошта мешаванд.",

        gallery_title: "Зебоии беназир",
        gallery_text: "Бо ин тасвирҳои зебо ба ҷаҳони ҷолиби Самарқанд ворид шавед.",
        gallery_shahi_zinda: "Шоҳи Зинда",
        gallery_ulugbek: "Расадхонаи Улуғбек",
        gallery_daniel: "Мақбараи Ҳазрати Дониёл",

        footer_text: "© 2025 Дар бораи Самарқанд. Ҳамаи ҳуқуқҳо маҳфузанд.",
        footer_contact: "Бо мо тамос гиред"
    },

    fa: {
        title: "درباره سمرقند - جواهر جاده ابریشم",
        header_title: "سمرقند",
        nav_history: "تاریخچه",
        nav_landmarks: "بناهای تاریخی",
        nav_museums: "موزه‌ها",
        nav_gallery: "گالری",
        hero_title: "کشف سمرقند",
        hero_text: "سفر به قلب جاده ابریشم، جایی که تاریخ و فرهنگ در شکوهی بی‌زمان درهم‌تنیده‌اند.",
        hero_cta: "اکنون کاوش کنید",

        history_title: "تاریخچه سمرقند",
        history_8bc_title: "قرن هشتم پیش از میلاد",
        history_8bc_text: "سمرقند با نام ماراکاندا تأسیس شد و پایتخت سغد شد، همان‌طور که در اوستای زرتشتی ذکر شده است.",
        history_sasanian_title: "قرن سوم تا هفتم",
        history_sasanian_text: "در دوره ساسانی، سمرقند همچنان یک مرکز فرهنگی و تجاری کلیدی در آسیای مرکزی بود.",
        history_329bc_title: "329 پیش از میلاد",
        history_329bc_text: "اسکندر مقدونی سمرقند را فتح کرد و ارزش استراتژیک آن را در جاده ابریشم بزرگ برجسته نمود.",
        history_samanid_title: "قرن نهم تا دهم",
        history_samanid_text: "در دوره امپراتوری سامانی، سمرقند به عنوان مرکز علم، پزشکی و ادبیات در عصر طلایی اسلام شکوفا شد.",
        history_14c_title: "قرن چهاردهم",
        history_14c_text: "امیر تیمور سمرقند را پایتخت امپراتوری خود کرد و عصر طلایی فرهنگ و معماری را آغاز نمود.",
        history_1868_title: "1868",
        history_1868_text: "نیروهای روس سمرقند را فتح کردند و آن را به امپراتوری روسیه ملحق نمودند.",
        history_1925_title: "1925–1939",
        history_1925_text: "سمرقند به عنوان پایتخت ازبکستان خدمت کرد و بعداً به عنوان میراث جهانی یونسکو ثبت شد.",

        landmarks_title: "بناها و شگفتی‌های تاریخی",
        landmarks_text: "شاهکارهای معماری سمرقند را با کاشی‌کاری‌های پیچیده و گنبدهای باشکوه کشف کنید.",
        landmark_registan_title: "میدان رجیستان",
        landmark_registan_text: "یک سایت میراث جهانی یونسکو، شامل مدارس علمیه اولوغ‌بیگ (1420)، شردار (1636) و طلاکاری (1660).",
        landmark_guremir_title: "آرامگاه گورامیر",
        landmark_guremir_text: "ساخته‌شده در سال 1404، این آرامگاه محل دفن امیر تیمور است و به خاطر گنبد فیروزه‌ای‌اش معروف است.",
        landmark_bibikhanum_title: "مسجد بی‌بی‌خانم",
        landmark_bibikhanum_text: "ساخته‌شده در سال 1404 برای همسر امیر تیمور، دارای یک سکوی قرآنی سنگی عظیم.",

        museums_title: "موزه‌های سمرقند",
        museums_text: "میراث غنی سمرقند را از طریق موزه‌های آن که آثار باستانی و داستان‌ها را حفظ می‌کنند، کاوش کنید.",
        museum_afrosiab_title: "موزه آفروسیاب",
        museum_afrosiab_text: "آثار قرن هشتم پیش از میلاد، از جمله نقاشی‌های دیواری کاخ سامانی، در نزدیکی سایت باستانی آفروسیاب را به نمایش می‌گذارد.",
        museum_ulugbek_title: "موزه رصدخانه اولوغ‌بیگ",
        museum_ulugbek_text: "دستاوردهای نجومی میرزا اولوغ‌بیگ در قرن پانزدهم را با رصدخانه بازسازی‌شده به نمایش می‌گذارد.",

        gallery_title: "شکوه بصری",
        gallery_text: "در زیبایی پرجنب‌وجوش سمرقند از طریق این تصاویر جذاب غوطه‌ور شوید.",
        gallery_shahi_zinda: "شاه زنده",
        gallery_ulugbek: "رصدخانه اولوغ‌بیگ",
        gallery_daniel: "آرامگاه حضرت دانیال",

        footer_text: "© 2025 درباره سمرقند. تمامی حقوق محفوظ است.",
        footer_contact: "تماس با ما"
    },

    ar: {
        title: "عن سمرقند - جوهرة طريق الحرير",
        header_title: "سمرقند",
        nav_history: "التاريخ",
        nav_landmarks: "المعالم",
        nav_museums: "المتاحف",
        nav_gallery: "المعرض",
        hero_title: "اكتشف سمرقند",
        hero_text: "سافر إلى قلب طريق الحرير، حيث تتشابك التاريخ والثقافة في روعة خالدة.",
        hero_cta: "استكشف الآن",

        history_title: "تاريخ سمرقند",
        history_8bc_title: "القرن الثامن قبل الميلاد",
        history_8bc_text: "تأسست باسم ماراكاندا، وأصبحت سمرقند عاصمة سغديانا، كما ورد في الأفستا الزرادشتية.",
        history_sasanian_title: "القرن الثالث إلى السابع",
        history_sasanian_text: "خلال العصر الساساني، بقيت سمرقند مركزًا ثقافيًا وتجاريًا رئيسيًا في آسيا الوسطى.",
        history_329bc_title: "329 قبل الميلاد",
        history_329bc_text: "فتح الإسكندر الأكبر سمرقند، مما أبرز قيمتها الاستراتيجية على طريق الحرير العظيم.",
        history_samanid_title: "القرن التاسع إلى العاشر",
        history_samanid_text: "في ظل الإمبراطورية السامانية، ازدهرت سمرقند كمركز للعلم والطب والأدب في العصر الذهبي الإسلامي.",
        history_14c_title: "القرن الرابع عشر",
        history_14c_text: "جعل أمير تيمور سمرقند عاصمة إمبراطوريته، مما أدى إلى عصر ذهبي للثقافة والعمارة.",
        history_1868_title: "1868",
        history_1868_text: "فتحت القوات الروسية سمرقند وضمّتها إلى الإمبراطورية الروسية.",
        history_1925_title: "1925–1939",
        history_1925_text: "خدمت سمرقند كعاصمة أوزبكستان، وأصبحت لاحقًا موقعًا للتراث العالمي لليونسكو.",

        landmarks_title: "المعالم والعجائب",
        landmarks_text: "اكتشف الأعمال المعمارية الرائعة في سمرقند، المزينة بأعمال البلاط المعقدة والقباب المهيبة.",
        landmark_registan_title: "ساحة ريجستان",
        landmark_registan_text: "موقع تراث عالمي لليونسكو، يضم المدارس العلمية: أولوغ بيك (1420)، شيردور (1636)، وتيليا-كاري (1660).",
        landmark_guremir_title: "ضريح غور أمير",
        landmark_guremir_text: "بُني في عام 1404، ويضم قبر أمير تيمور، ويشتهر بقبته الفيروزية.",
        landmark_bibikhanum_title: "مسجد بيبي خانوم",
        landmark_bibikhanum_text: "بُني في عام 1404 لزوجة أمير تيمور، ويتميز بمنصة قرآنية حجرية ضخمة.",

        museums_title: "متاحف سمرقند",
        museums_text: "استكشف تراث سمرقند الغني من خلال متاحفها التي تحفظ القطع الأثرية والقصص القديمة.",
        museum_afrosiab_title: "متحف أفروسياب",
        museum_afrosiab_text: "يعرض قطعًا أثرية من القرن الثامن قبل الميلاد، بما في ذلك جداريات قصر السامانيين، بالقرب من موقع أفروسياب القديم.",
        museum_ulugbek_title: "متحف مرصد أولوغ بيك",
        museum_ulugbek_text: "يبرز إنجازات أولوغ بيك الفلكية في القرن الخامس عشر مع مرصد مُعاد بناؤه.",

        gallery_title: "روعة بصرية",
        gallery_text: "انغمس في جمال سمرقند النابض بالحياة من خلال هذه الصور الآسرة.",
        gallery_shahi_zinda: "شاهي زيندا",
        gallery_ulugbek: "مرصد أولوغ بيك",
        gallery_daniel: "ضريح النبي دانيال",

        footer_text: "© 2025 عن سمرقند. جميع الحقوق محفوظة.",
        footer_contact: "اتصل بنا"
    },

    hi: {
        title: "समरकंद के बारे में - सिल्क रोड का रत्न",
        header_title: "समरकंद",
        nav_history: "इतिहास",
        nav_landmarks: "स्थलचिह्न",
        nav_museums: "संग्रहालय",
        nav_gallery: "गैलरी",
        hero_title: "समरकंद की खोज करें",
        hero_text: "सिल्क रोड के दिल में यात्रा करें, जहाँ इतिहास और संस्कृति समयातीत वैभव में एक साथ जुड़ते हैं।",
        hero_cta: "अब खोजें",

        history_title: "समरकंद का इतिहास",
        history_8bc_title: "8वीं शताब्दी ईसा पूर्व",
        history_8bc_text: "माराकंदा के रूप में स्थापित, समरकंद सोग्डियाना की राजधानी बन गया, जैसा कि ज़ोरोस्ट्रियन 'अवेस्ता' में उल्लेखित है।",
        history_sasanian_title: "3री से 7वीं शताब्दी",
        history_sasanian_text: "सासानी युग के दौरान, समरकंद मध्य एशिया का एक प्रमुख सांस्कृतिक और व्यापारिक केंद्र बना रहा।",
        history_329bc_title: "329 ईसा पूर्व",
        history_329bc_text: "सिकंदर महान ने समरकंद पर विजय प्राप्त की, जिससे इसकी महान सिल्क रोड पर रणनीतिक महत्व को उजागर किया गया।",
        history_samanid_title: "9वीं–10वीं शताब्दी",
        history_samanid_text: "सामानी साम्राज्य के तहत, समरकंद इस्लामी स्वर्ण युग में विज्ञान, चिकित्सा और साहित्य का केंद्र बनकर फला-फूला।",
        history_14c_title: "14वीं शताब्दी",
        history_14c_text: "अमीर तैमूर ने समरकंद को अपनी साम्राज्य की राजधानी बनाया, जिससे संस्कृति और वास्तुकला का स्वर्ण युग शुरू हुआ।",
        history_1868_title: "1868",
        history_1868_text: "रूसी सेनाओं ने समरकंद पर कब्जा किया और इसे रूसी साम्राज्य में शामिल किया।",
        history_1925_title: "1925–1939",
        history_1925_text: "समरकंद ने उज़्बेकिस्तान की राजधानी के रूप में कार्य किया, बाद में इसे यूनेस्को विश्व धरोहर स्थल के रूप में नामित किया गया।",

        landmarks_title: "स्थलचिह्न और आश्चर्य",
        landmarks_text: "समरकंद के वास्तुशिल्पीय उत्कृष्ट कृतियों की खोज करें, जो जटिल टाइलवर्क और भव्य गुंबदों से सजी हैं।",
        landmark_registan_title: "रेजिस्तान चौक",
        landmark_registan_text: "एक यूनेस्को विश्व धरोहर स्थल, जिसमें उलुगबेक (1420), शेरदोर (1636), और तिल्या-कारी (1660) मदरसे शामिल हैं।",
        landmark_guremir_title: "गुर-ए-अमीर मकबरा",
        landmark_guremir_text: "1404 में निर्मित, यह मकबरा अमीर तैमूर की समाधि का घर है, जो अपने फ़िरोज़ी गुंबद के लिए प्रसिद्ध है।",
        landmark_bibikhanum_title: "बीबी-खानम मस्जिद",
        landmark_bibikhanum_text: "1404 में अमीर तैमूर की पत्नी के लिए निर्मित, जिसमें एक विशाल पत्थर का कुरान मंच है।",

        museums_title: "समरकंद के संग्रहालय",
        museums_text: "समरकंद की समृद्ध विरासत को इसके संग्रहालयों के माध्यम से खोजें, जो प्राचीन कलाकृतियों और कहानियों को संरक्षित करते हैं।",
        museum_afrosiab_title: "अफ्रोसियाब संग्रहालय",
        museum_afrosiab_text: "8वीं शताब्दी ईसा पूर्व की कलाकृतियाँ प्रदर्शित करता है, जिसमें सामानी महल के भित्ति चित्र शामिल हैं, जो प्राचीन अफ्रोसियाब स्थल के निकट है।",
        museum_ulugbek_title: "उलुगबेक वेधशाला संग्रहालय",
        museum_ulugbek_text: "15वीं शताब्दी में मिर्ज़ा उलुगबेक की खगोलीय उपलब्धियों को पुनर्निर्मित वेधशाला के साथ प्रदर्शित करता है।",

        gallery_title: "दृश्य वैभव",
        gallery_text: "इन मनोरम छवियों के माध्यम से समरकंद की जीवंत सुंदरता में डूब जाएँ।",
        gallery_shahi_zinda: "शाही ज़िंदा",
        gallery_ulugbek: "उलुगबेक वेधशाला",
        gallery_daniel: "संत डैनियल का मकबरा",

        footer_text: "© 2025 समरकंद के बारे में। सर्वाधिकार सुरक्षित।",
        footer_contact: "हमसे संपर्क करें"
    },

    zh: {
        title: "关于撒马尔罕 - 丝绸之路的明珠",
        header_title: "撒马尔罕",
        nav_history: "历史",
        nav_landmarks: "地标",
        nav_museums: "博物馆",
        nav_gallery: "画廊",
        hero_title: "探索撒马尔罕",
        hero_text: "踏上丝绸之路的核心之旅，这里历史与文化在永恒的辉煌中交织。",
        hero_cta: "立即探索",

        history_title: "撒马尔罕的历史",
        history_8bc_title: "公元前8世纪",
        history_8bc_text: "撒马尔罕以马拉坎达之名建立，成为索格底亚纳的首都，如琐罗亚斯德教《阿维斯塔》中所述。",
        history_sasanian_title: "3世纪至7世纪",
        history_sasanian_text: "在萨珊王朝时期，撒马尔罕仍是中亚重要的文化和贸易中心。",
        history_329bc_title: "公元前329年",
        history_329bc_text: "亚历山大大帝征服撒马尔罕，凸显了其在伟大丝绸之路上的战略价值。",
        history_samanid_title: "9世纪至10世纪",
        history_samanid_text: "在萨曼王朝统治下，撒马尔罕成为伊斯兰黄金时代的科学、医学和文学中心，蓬勃发展。",
        history_14c_title: "14世纪",
        history_14c_text: "阿米尔·帖木儿将撒马尔罕定为帝国首都，开启了文化和建筑的黄金时代。",
        history_1868_title: "1868年",
        history_1868_text: "俄罗斯军队征服撒马尔罕，将其并入俄罗斯帝国。",
        history_1925_title: "1925-1939年",
        history_1925_text: "撒马尔罕作为乌兹别克斯坦的首都，后被列为联合国教科文组织世界遗产地。",

        landmarks_title: "地标与奇迹",
        landmarks_text: "探索撒马尔罕的建筑杰作，装饰着精美的瓷砖工艺和壮丽的圆顶。",
        landmark_registan_title: "列吉斯坦广场",
        landmark_registan_text: "联合国教科文组织世界遗产地，包括乌鲁伯克（1420年）、谢尔多尔（1636年）和提利亚-卡里（1660年）三座神学院。",
        landmark_guremir_title: "古尔-艾米尔陵墓",
        landmark_guremir_text: "建于1404年，这座陵墓是阿米尔·帖木儿的墓地，以其碧绿圆顶而闻名。",
        landmark_bibikhanum_title: "比比-哈努姆清真寺",
        landmark_bibikhanum_text: "1404年为阿米尔·帖木儿的妻子所建，拥有巨大的石质古兰经平台。",

        museums_title: "撒马尔罕的博物馆",
        museums_text: "通过撒马尔罕的博物馆探索其丰富的遗产，保存着古老文物和故事。",
        museum_afrosiab_title: "阿夫罗西亚布博物馆",
        museum_afrosiab_text: "展示公元前8世纪的文物，包括萨曼尼德宫殿壁画，位于古老的阿夫罗西亚布遗址附近。",
        museum_ulugbek_title: "乌鲁伯克天文台博物馆",
        museum_ulugbek_text: "展示15世纪米尔扎·乌鲁伯克的天文成就，配有重建的天文台。",

        gallery_title: "视觉盛宴",
        gallery_text: "通过这些迷人的图片沉浸在撒马尔罕的生动美丽中。",
        gallery_shahi_zinda: "沙赫-津达",
        gallery_ulugbek: "乌鲁伯克天文台",
        gallery_daniel: "圣但以理墓",

        footer_text: "© 2025 关于撒马尔罕。版权所有。",
        footer_contact: "联系我们"
    },

    de: {
        title: "Über Samarkand - Juwel der Seidenstraße",
        header_title: "Samarkand",
        nav_history: "Geschichte",
        nav_landmarks: "Sehenswürdigkeiten",
        nav_museums: "Museen",
        nav_gallery: "Galerie",
        hero_title: "Entdecken Sie Samarkand",
        hero_text: "Reisen Sie ins Herz der Seidenstraße, wo Geschichte und Kultur in zeitloser Pracht verschmelzen.",
        hero_cta: "Jetzt erkunden",

        history_title: "Geschichte von Samarkand",
        history_8bc_title: "8. Jahrhundert v. Chr.",
        history_8bc_text: "Als Marakanda gegründet, wird Samarkand die Hauptstadt von Sogdien, wie im zoroastrischen 'Avesta' erwähnt.",
        history_sasanian_title: "3.–7. Jahrhundert",
        history_sasanian_text: "Während der sasanidischen Ära blieb Samarkand ein zentrales kulturelles und Handelszentrum Zentralasiens.",
        history_329bc_title: "329 v. Chr.",
        history_329bc_text: "Alexander der Große erobert Samarkand und unterstreicht seinen strategischen Wert entlang der Großen Seidenstraße.",
        history_samanid_title: "9.–10. Jahrhundert",
        history_samanid_text: "Unter dem Samanidenreich blüht Samarkand als Zentrum für Wissenschaft, Medizin und Literatur im Islamischen Goldenen Zeitalter auf.",
        history_14c_title: "14. Jahrhundert",
        history_14c_text: "Amir Timur macht Samarkand zur Hauptstadt seines Reiches und leitet ein goldenes Zeitalter der Kultur und Architektur ein.",
        history_1868_title: "1868",
        history_1868_text: "Russische Truppen erobern Samarkand und integrieren es in das Russische Reich.",
        history_1925_title: "1925–1939",
        history_1925_text: "Samarkand dient als Hauptstadt Usbekistans und wird später zum UNESCO-Weltkulturerbe erklärt.",

        landmarks_title: "Sehenswürdigkeiten & Wunder",
        landmarks_text: "Entdecken Sie Samarkands architektonische Meisterwerke, verziert mit filigranen Fliesenarbeiten und majestätischen Kuppeln.",
        landmark_registan_title: "Registan-Platz",
        landmark_registan_text: "Ein UNESCO-Weltkulturerbe, bestehend aus den Medresen Ulugbek (1420), Sherdor (1636) und Tillya-Kari (1660).",
        landmark_guremir_title: "Gur-Emir-Mausoleum",
        landmark_guremir_text: "Erbaut 1404, beherbergt dieses Mausoleum das Grab von Amir Timur und ist bekannt für seine türkisfarbene Kuppel.",
        landmark_bibikhanum_title: "Bibi-Khanum-Moschee",
        landmark_bibikhanum_text: "1404 für Amir Timurs Frau erbaut, mit einer großen steinernen Koran-Plattform.",

        museums_title: "Museen von Samarkand",
        museums_text: "Erkunden Sie Samarkands reiches Erbe durch seine Museen, die antike Artefakte und Geschichten bewahren.",
        museum_afrosiab_title: "Afrosiab-Museum",
        museum_afrosiab_text: "Zeigt Artefakte aus dem 8. Jahrhundert v. Chr., einschließlich Fresken des Samanidenpalastes, nahe der antiken Stätte Afrosiab.",
        museum_ulugbek_title: "Ulugbek-Observatorium-Museum",
        museum_ulugbek_text: "Präsentiert die astronomischen Errungenschaften von Mirzo Ulugbek im 15. Jahrhundert mit einem rekonstruierten Observatorium.",

        gallery_title: "Visuelle Pracht",
        gallery_text: "Tauchen Sie ein in die lebendige Schönheit Samarkands durch diese faszinierenden Bilder.",
        gallery_shahi_zinda: "Shahi Zinda",
        gallery_ulugbek: "Ulugbek-Observatorium",
        gallery_daniel: "Grab des Heiligen Daniel",

        footer_text: "© 2025 Über Samarkand. Alle Rechte vorbehalten.",
        footer_contact: "Kontaktieren Sie uns"
    },

    fr: {
        title: "À propos de Samarcande - Joyau de la Route de la Soie",
        header_title: "Samarcande",
        nav_history: "Histoire",
        nav_landmarks: "Monuments",
        nav_museums: "Musées",
        nav_gallery: "Galerie",
        hero_title: "Découvrez Samarcande",
        hero_text: "Voyagez au cœur de la Route de la Soie, où histoire et culture s’entrelacent dans une splendeur intemporelle.",
        hero_cta: "Explorez maintenant",

        history_title: "Histoire de Samarcande",
        history_8bc_title: "8e siècle av. J.-C.",
        history_8bc_text: "Fondée sous le nom de Maracanda, Samarcande devient la capitale de la Sogdiane, comme mentionné dans l’Avesta zoroastrien.",
        history_sasanian_title: "3e–7e siècle",
        history_sasanian_text: "Pendant l’ère sassanide, Samarcande reste un centre culturel et commercial clé de l’Asie centrale.",
        history_329bc_title: "329 av. J.-C.",
        history_329bc_text: "Alexandre le Grand conquiert Samarcande, mettant en lumière sa valeur stratégique sur la Grande Route de la Soie.",
        history_samanid_title: "9e–10e siècle",
        history_samanid_text: "Sous l’Empire samanide, Samarcande prospère comme centre de science, de médecine et de littérature à l’âge d’or islamique.",
        history_14c_title: "14e siècle",
        history_14c_text: "Amir Timour fait de Samarcande la capitale de son empire, inaugurant un âge d’or de la culture et de l’architecture.",
        history_1868_title: "1868",
        history_1868_text: "Les forces russes conquièrent Samarcande, l’intégrant à l’Empire russe.",
        history_1925_title: "1925–1939",
        history_1925_text: "Samarcande sert de capitale de l’Ouzbékistan, avant d’être inscrite au patrimoine mondial de l’UNESCO.",

        landmarks_title: "Monuments et merveilles",
        landmarks_text: "Découvrez les chefs-d’œuvre architecturaux de Samarcande, ornés de carrelages complexes et de dômes majestueux.",
        landmark_registan_title: "Place du Régistan",
        landmark_registan_text: "Site du patrimoine mondial de l’UNESCO, comprenant les madrasas Ulugbek (1420), Sherdor (1636) et Tillya-Kari (1660).",
        landmark_guremir_title: "Mausolée de Gour-Emir",
        landmark_guremir_text: "Construit en 1404, ce mausolée abrite la tombe d’Amir Timour, célèbre pour son dôme turquoise.",
        landmark_bibikhanum_title: "Mosquée Bibi-Khanum",
        landmark_bibikhanum_text: "Construite en 1404 pour l’épouse d’Amir Timour, avec une plateforme de Coran en pierre imposante.",

        museums_title: "Musées de Samarcande",
        museums_text: "Explorez le riche patrimoine de Samarcande à travers ses musées, qui préservent des artefacts anciens et des histoires.",
        museum_afrosiab_title: "Musée d’Afrosiab",
        museum_afrosiab_text: "Présente des artefacts du 8e siècle av. J.-C., y compris des fresques du palais samanide, près du site antique d’Afrosiab.",
        museum_ulugbek_title: "Musée de l’Observatoire d’Ulugbek",
        museum_ulugbek_text: "Met en lumière les réalisations astronomiques de Mirzo Ulugbek au 15e siècle avec un observatoire reconstruit.",

        gallery_title: "Splendeur visuelle",
        gallery_text: "Plongez dans la beauté vibrante de Samarcande à travers ces images captivantes.",
        gallery_shahi_zinda: "Shahi Zinda",
        gallery_ulugbek: "Observatoire d’Ulugbek",
        gallery_daniel: "Tombeau de Saint Daniel",

        footer_text: "© 2025 À propos de Samarcande. Tous droits réservés.",
        footer_contact: "Contactez-nous"
    }
};

let currentLang = localStorage.getItem('selectedLanguage') || 'en';

function updateLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('selectedLanguage', lang);

    document.querySelectorAll('[data-lang-key]').forEach(element => {
        const key = element.getAttribute('data-lang-key');
        element.textContent = translations[lang][key] || '';
    });

    document.querySelector('html').lang = lang;
    document.title = translations[lang].title || 'About Samarkand';
}

document.querySelector('.lang-select').addEventListener('change', (e) => {
    updateLanguage(e.target.value);
});

document.querySelector('.lang-select').value = currentLang;
updateLanguage(currentLang);